# Generated by Django 5.1.6 on 2025-03-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qadi',
            fields=[
                ('qadi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('court_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('experience_years', models.IntegerField()),
            ],
        ),
    ]
