# Generated by Django 5.1.6 on 2025-03-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_caseresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadi',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
