# Generated by Django 5.1.6 on 2025-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_qadi_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('passport_no', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('lost_company', models.CharField(max_length=255)),
                ('lose_amount', models.FloatField()),
                ('lost_year', models.IntegerField()),
            ],
        ),
    ]
